default: &defaults
  validation_key_path: 'config/validation.pem'
  chef_client_interval: 20
  webserver_port: 80
  application_port: 80
  load_balancer_protocol: 'HTTP'
  environment_allowed_chars: /[a-zA-Z0-9-\s]/
  status_check_interval: 5

development:
  <<: *defaults
  chef_server_url: 'localhost:4000'

production:
  <<: *defaults
  chef_server_url: 'http://ec2-23-20-146-55.compute-1.amazonaws.com:4000'

test:
  <<: *defaults
  chef_server_url: 'localhost:4000'
