default: &defaults
  validation_key_path: 'config/validation.pem'
  chef_client_interval: 20
  webserver_port: 80
  application_port: 80
  load_balancer_protocol: 'HTTP'
  status_check_interval: 5
  s3_access_control: ["Private","PublicRead","PublicReadWrite","AuthenticatedRead","BucketOwnerRead","BucketOwnerFullControl"]  
development:
  <<: *defaults
  chef_server_url: 'localhost:4000'

production:
  <<: *defaults
  chef_server_url: 'http://ec2-184-73-196-133.compute-1.amazonaws.com:4000'

test:
  <<: *defaults
  chef_server_url: 'localhost:4000'
