default: &defaults
  validation_key_path: 'config/validation.pem'
  chef_client_interval: 180
  chef_validation_client_name: 'chef-validator'
  webserver_port: 80
  application_port: 80
  load_balancer_protocol: 'HTTP'
  status_check_interval: 5
  s3_access_control: ["Private","PublicRead","PublicReadWrite","AuthenticatedRead","BucketOwnerRead","BucketOwnerFullControl"]
  java_versions: ["6","7"]
  strings_max_length: 10
  attr_encryption_salt: 'random string'

development:
  <<: *defaults
  chef_server_url: 'https://api.opscode.com/organizations/neevtech-test'
  chef_validation_client_name: 'neevtech-test-validator'

production:
  <<: *defaults
  chef_server_url: 'http://ec2-184-73-196-133.compute-1.amazonaws.com:4000'
  attr_encryption_salt: ''

test:
  <<: *defaults
  chef_server_url: 'localhost:4000'
