default: &defaults
  validation_key_path: 'config/validation.pem'
  chef_client_interval: 20
  webserver_port: 80
  application_port: 8080
  load_balancer_protocol: 'HTTP'
  
development:
  <<: *defaults
  chef_server_url: 'http://ec2-23-20-173-176.compute-1.amazonaws.com:4000'

production:
  <<: *defaults
  chef_server_url: 'http://ec2-23-20-173-176.compute-1.amazonaws.com:4000'
